# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesAndFeaturesWidget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(655, 845)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolBox = QtGui.QToolBox(Form)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 302, 290))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.loadResults = QtGui.QPushButton(self.page)
        self.loadResults.setObjectName(_fromUtf8("loadResults"))
        self.horizontalLayout_6.addWidget(self.loadResults)
        self.closeResults = QtGui.QPushButton(self.page)
        self.closeResults.setObjectName(_fromUtf8("closeResults"))
        self.horizontalLayout_6.addWidget(self.closeResults)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.openDataFilesTable = QtGui.QTableWidget(self.page)
        self.openDataFilesTable.setObjectName(_fromUtf8("openDataFilesTable"))
        self.openDataFilesTable.setColumnCount(2)
        self.openDataFilesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.openDataFilesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.openDataFilesTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.openDataFilesTable)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_3 = QtGui.QPushButton(self.page)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.page)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.groupBox_6 = QtGui.QGroupBox(self.page)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.sampleInformation = QtGui.QTableWidget(self.groupBox_6)
        self.sampleInformation.setObjectName(_fromUtf8("sampleInformation"))
        self.sampleInformation.setColumnCount(0)
        self.sampleInformation.setRowCount(0)
        self.gridLayout_7.addWidget(self.sampleInformation, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 637, 765))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout = QtGui.QGridLayout(self.page_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_13 = QtGui.QLabel(self.page_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.allFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.allFeaturesRB.setObjectName(_fromUtf8("allFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.allFeaturesRB)
        self.unassignedFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.unassignedFeaturesRB.setChecked(True)
        self.unassignedFeaturesRB.setObjectName(_fromUtf8("unassignedFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.unassignedFeaturesRB)
        self.acceptedFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.acceptedFeaturesRB.setObjectName(_fromUtf8("acceptedFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.acceptedFeaturesRB)
        self.rejectedFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.rejectedFeaturesRB.setObjectName(_fromUtf8("rejectedFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.rejectedFeaturesRB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.xcmsFeatures = QtGui.QTableWidget(self.page_3)
        self.xcmsFeatures.setObjectName(_fromUtf8("xcmsFeatures"))
        self.xcmsFeatures.setColumnCount(5)
        self.xcmsFeatures.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.xcmsFeatures)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.upButton = QtGui.QPushButton(self.page_3)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.horizontalLayout_2.addWidget(self.upButton)
        self.downButton = QtGui.QPushButton(self.page_3)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.horizontalLayout_2.addWidget(self.downButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.saveResults = QtGui.QPushButton(self.page_3)
        self.saveResults.setObjectName(_fromUtf8("saveResults"))
        self.verticalLayout.addWidget(self.saveResults)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.loadResults.setText(_translate("Form", "Load Results File", None))
        self.closeResults.setText(_translate("Form", "Close Results File", None))
        item = self.openDataFilesTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "#", None))
        item = self.openDataFilesTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "File", None))
        self.pushButton_3.setText(_translate("Form", "Move Up", None))
        self.pushButton_4.setText(_translate("Form", "Move Down", None))
        self.groupBox_6.setTitle(_translate("Form", "Sample Information", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Form", "XCMS Results Files", None))
        self.label_13.setText(_translate("Form", "Feature Type", None))
        self.allFeaturesRB.setText(_translate("Form", "All", None))
        self.unassignedFeaturesRB.setText(_translate("Form", "Unassigned", None))
        self.acceptedFeaturesRB.setText(_translate("Form", "Accepted", None))
        self.rejectedFeaturesRB.setText(_translate("Form", "Rejected", None))
        item = self.xcmsFeatures.horizontalHeaderItem(0)
        item.setText(_translate("Form", "File", None))
        item = self.xcmsFeatures.horizontalHeaderItem(1)
        item.setText(_translate("Form", "#", None))
        item = self.xcmsFeatures.horizontalHeaderItem(2)
        item.setText(_translate("Form", "RT", None))
        item = self.xcmsFeatures.horizontalHeaderItem(3)
        item.setText(_translate("Form", "m/z", None))
        item = self.xcmsFeatures.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Score", None))
        self.upButton.setText(_translate("Form", "Up", None))
        self.downButton.setText(_translate("Form", "Down", None))
        self.saveResults.setText(_translate("Form", "Save Results", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Form", "Features", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

