# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchAlignmentGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1269, 900)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tab)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.splitter_5 = QtGui.QSplitter(self.tab)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.layoutWidget = QtGui.QWidget(self.splitter_5)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.loadBatchesButton = QtGui.QPushButton(self.layoutWidget)
        self.loadBatchesButton.setObjectName(_fromUtf8("loadBatchesButton"))
        self.horizontalLayout_5.addWidget(self.loadBatchesButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.batchFileTable = QtGui.QTableWidget(self.layoutWidget)
        self.batchFileTable.setObjectName(_fromUtf8("batchFileTable"))
        self.batchFileTable.setColumnCount(3)
        self.batchFileTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.batchFileTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.batchFileTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.batchFileTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_14.addWidget(self.batchFileTable)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.ppmTol = QtGui.QLineEdit(self.layoutWidget)
        self.ppmTol.setObjectName(_fromUtf8("ppmTol"))
        self.gridLayout_2.addWidget(self.ppmTol, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.rtTol = QtGui.QLineEdit(self.layoutWidget)
        self.rtTol.setObjectName(_fromUtf8("rtTol"))
        self.gridLayout_2.addWidget(self.rtTol, 2, 1, 1, 1)
        self.runAlignmentButton = QtGui.QPushButton(self.layoutWidget)
        self.runAlignmentButton.setObjectName(_fromUtf8("runAlignmentButton"))
        self.gridLayout_2.addWidget(self.runAlignmentButton, 3, 0, 1, 2)
        self.verticalLayout_14.addLayout(self.gridLayout_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.selectLibraryFile = QtGui.QPushButton(self.layoutWidget)
        self.selectLibraryFile.setObjectName(_fromUtf8("selectLibraryFile"))
        self.verticalLayout.addWidget(self.selectLibraryFile)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.posIonCB = QtGui.QRadioButton(self.layoutWidget)
        self.posIonCB.setObjectName(_fromUtf8("posIonCB"))
        self.gridLayout_20.addWidget(self.posIonCB, 4, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_20.addWidget(self.label_17, 0, 0, 1, 1)
        self.annotationppmTol = QtGui.QLineEdit(self.layoutWidget)
        self.annotationppmTol.setObjectName(_fromUtf8("annotationppmTol"))
        self.gridLayout_20.addWidget(self.annotationppmTol, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_20.addWidget(self.label_15, 2, 0, 1, 1)
        self.annotationrtTol = QtGui.QLineEdit(self.layoutWidget)
        self.annotationrtTol.setObjectName(_fromUtf8("annotationrtTol"))
        self.gridLayout_20.addWidget(self.annotationrtTol, 2, 1, 1, 2)
        self.libraryFileDisplay = QtGui.QLabel(self.layoutWidget)
        self.libraryFileDisplay.setText(_fromUtf8(""))
        self.libraryFileDisplay.setObjectName(_fromUtf8("libraryFileDisplay"))
        self.gridLayout_20.addWidget(self.libraryFileDisplay, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_20.addWidget(self.label_14, 1, 0, 1, 2)
        self.negIonCB = QtGui.QRadioButton(self.layoutWidget)
        self.negIonCB.setChecked(True)
        self.negIonCB.setObjectName(_fromUtf8("negIonCB"))
        self.gridLayout_20.addWidget(self.negIonCB, 5, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_20.addWidget(self.label_18, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_20)
        self.doConsensusAnnotation = QtGui.QPushButton(self.layoutWidget)
        self.doConsensusAnnotation.setObjectName(_fromUtf8("doConsensusAnnotation"))
        self.verticalLayout.addWidget(self.doConsensusAnnotation)
        self.verticalLayout_14.addLayout(self.verticalLayout)
        self.featureMap = GraphicsLayoutWidget(self.splitter_5)
        self.featureMap.setObjectName(_fromUtf8("featureMap"))
        self.gridLayout_21.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.batchDetails = QtGui.QTableWidget(self.tab_3)
        self.batchDetails.setObjectName(_fromUtf8("batchDetails"))
        self.batchDetails.setColumnCount(9)
        self.batchDetails.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.batchDetails.setHorizontalHeaderItem(8, item)
        self.gridLayout_8.addWidget(self.batchDetails, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget_2 = QtGui.QTabWidget(self.splitter)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabWidget_2Page2 = QtGui.QWidget()
        self.tabWidget_2Page2.setObjectName(_fromUtf8("tabWidget_2Page2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabWidget_2Page2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.tabWidget_2Page2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.featureAlignment = GraphicsLayoutWidget(self.tabWidget_2Page2)
        self.featureAlignment.setObjectName(_fromUtf8("featureAlignment"))
        self.verticalLayout_2.addWidget(self.featureAlignment)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.tabWidget_2Page2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.intensityMap = GraphicsLayoutWidget(self.tabWidget_2Page2)
        self.intensityMap.setObjectName(_fromUtf8("intensityMap"))
        self.verticalLayout_3.addWidget(self.intensityMap)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tabWidget_2Page2, _fromUtf8(""))
        self.Sample = QtGui.QWidget()
        self.Sample.setObjectName(_fromUtf8("Sample"))
        self.gridLayout_6 = QtGui.QGridLayout(self.Sample)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.splitter_3 = QtGui.QSplitter(self.Sample)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.filledOnly = QtGui.QCheckBox(self.layoutWidget1)
        self.filledOnly.setObjectName(_fromUtf8("filledOnly"))
        self.horizontalLayout_4.addWidget(self.filledOnly)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.sampleDetails = QtGui.QTableWidget(self.layoutWidget1)
        self.sampleDetails.setObjectName(_fromUtf8("sampleDetails"))
        self.sampleDetails.setColumnCount(7)
        self.sampleDetails.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.sampleDetails.setHorizontalHeaderItem(6, item)
        self.verticalLayout_5.addWidget(self.sampleDetails)
        self.layoutWidget2 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.activeBatchesGroupBox = QtGui.QGroupBox(self.layoutWidget2)
        self.activeBatchesGroupBox.setObjectName(_fromUtf8("activeBatchesGroupBox"))
        self.verticalLayout_6.addWidget(self.activeBatchesGroupBox)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.reIntegrateRegion = QtGui.QPushButton(self.groupBox)
        self.reIntegrateRegion.setObjectName(_fromUtf8("reIntegrateRegion"))
        self.gridLayout_10.addWidget(self.reIntegrateRegion, 0, 0, 1, 1)
        self.restoreDefaultIntegrationButton = QtGui.QPushButton(self.groupBox)
        self.restoreDefaultIntegrationButton.setObjectName(_fromUtf8("restoreDefaultIntegrationButton"))
        self.gridLayout_10.addWidget(self.restoreDefaultIntegrationButton, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.assignmentTable = QtGui.QTableWidget(self.layoutWidget2)
        self.assignmentTable.setObjectName(_fromUtf8("assignmentTable"))
        self.assignmentTable.setColumnCount(3)
        self.assignmentTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assignmentTable.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.assignmentTable, 1, 0, 1, 2)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.updateAssignment = QtGui.QPushButton(self.layoutWidget2)
        self.updateAssignment.setObjectName(_fromUtf8("updateAssignment"))
        self.gridLayout_4.addWidget(self.updateAssignment, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.selectedSamplesOnly = QtGui.QCheckBox(self.layoutWidget3)
        self.selectedSamplesOnly.setObjectName(_fromUtf8("selectedSamplesOnly"))
        self.horizontalLayout_3.addWidget(self.selectedSamplesOnly)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.eicTrace = GraphicsLayoutWidget(self.layoutWidget3)
        self.eicTrace.setObjectName(_fromUtf8("eicTrace"))
        self.verticalLayout_4.addWidget(self.eicTrace)
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.msTrace = GraphicsLayoutWidget(self.layoutWidget3)
        self.msTrace.setObjectName(_fromUtf8("msTrace"))
        self.verticalLayout_4.addWidget(self.msTrace)
        self.gridLayout_6.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.Sample, _fromUtf8(""))
        self.layoutWidget4 = QtGui.QWidget(self.splitter)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_8.addWidget(self.label)
        self.recoverALLMissingConsensusCandidatesButton = QtGui.QPushButton(self.layoutWidget4)
        self.recoverALLMissingConsensusCandidatesButton.setObjectName(_fromUtf8("recoverALLMissingConsensusCandidatesButton"))
        self.horizontalLayout_8.addWidget(self.recoverALLMissingConsensusCandidatesButton)
        self.recoverMissingConsensusCandidatesButton = QtGui.QPushButton(self.layoutWidget4)
        self.recoverMissingConsensusCandidatesButton.setObjectName(_fromUtf8("recoverMissingConsensusCandidatesButton"))
        self.horizontalLayout_8.addWidget(self.recoverMissingConsensusCandidatesButton)
        self.deleteConsensusGroupButton = QtGui.QPushButton(self.layoutWidget4)
        self.deleteConsensusGroupButton.setObjectName(_fromUtf8("deleteConsensusGroupButton"))
        self.horizontalLayout_8.addWidget(self.deleteConsensusGroupButton)
        self.undoDeleteConsensusGroupButton = QtGui.QPushButton(self.layoutWidget4)
        self.undoDeleteConsensusGroupButton.setObjectName(_fromUtf8("undoDeleteConsensusGroupButton"))
        self.horizontalLayout_8.addWidget(self.undoDeleteConsensusGroupButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.consensusFeatures = QtGui.QTableWidget(self.layoutWidget4)
        self.consensusFeatures.setObjectName(_fromUtf8("consensusFeatures"))
        self.consensusFeatures.setColumnCount(7)
        self.consensusFeatures.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.consensusFeatures.setHorizontalHeaderItem(6, item)
        self.verticalLayout_7.addWidget(self.consensusFeatures)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 1, 0, 2, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.outputFileName = QtGui.QLineEdit(self.tab_4)
        self.outputFileName.setObjectName(_fromUtf8("outputFileName"))
        self.horizontalLayout_6.addWidget(self.outputFileName)
        self.browseResults = QtGui.QPushButton(self.tab_4)
        self.browseResults.setObjectName(_fromUtf8("browseResults"))
        self.horizontalLayout_6.addWidget(self.browseResults)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 1, 1, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 1, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_11.addItem(spacerItem10, 2, 1, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_16 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.csvOutputCB = QtGui.QCheckBox(self.tab_4)
        self.csvOutputCB.setObjectName(_fromUtf8("csvOutputCB"))
        self.horizontalLayout_7.addWidget(self.csvOutputCB)
        self.xlsxOutputCB = QtGui.QCheckBox(self.tab_4)
        self.xlsxOutputCB.setObjectName(_fromUtf8("xlsxOutputCB"))
        self.horizontalLayout_7.addWidget(self.xlsxOutputCB)
        self.gridLayout_11.addLayout(self.horizontalLayout_7, 3, 1, 1, 2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem11, 4, 1, 1, 1)
        self.saveResults = QtGui.QPushButton(self.tab_4)
        self.saveResults.setObjectName(_fromUtf8("saveResults"))
        self.gridLayout_11.addWidget(self.saveResults, 4, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_2.setText(_translate("Dialog", "Batch Files", None))
        self.loadBatchesButton.setText(_translate("Dialog", "Load Batches", None))
        item = self.batchFileTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Batch", None))
        item = self.batchFileTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name", None))
        item = self.batchFileTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Features", None))
        self.label_12.setText(_translate("Dialog", "Alignment", None))
        self.label_5.setText(_translate("Dialog", "ppm Tol", None))
        self.ppmTol.setText(_translate("Dialog", "30", None))
        self.label_6.setText(_translate("Dialog", "RT Tol", None))
        self.rtTol.setText(_translate("Dialog", "200", None))
        self.runAlignmentButton.setText(_translate("Dialog", "Run alignment", None))
        self.label_13.setText(_translate("Dialog", "Annotation", None))
        self.selectLibraryFile.setText(_translate("Dialog", "Select Library File", None))
        self.posIonCB.setText(_translate("Dialog", "Pos", None))
        self.label_17.setText(_translate("Dialog", "Library", None))
        self.annotationppmTol.setText(_translate("Dialog", "30", None))
        self.label_15.setText(_translate("Dialog", "RT Tol", None))
        self.annotationrtTol.setText(_translate("Dialog", "200", None))
        self.label_14.setText(_translate("Dialog", "ppm Tol", None))
        self.negIonCB.setText(_translate("Dialog", "Neg", None))
        self.label_18.setText(_translate("Dialog", "Polarity", None))
        self.doConsensusAnnotation.setText(_translate("Dialog", "Run Annotation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Input Data", None))
        item = self.batchDetails.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Batch #", None))
        item = self.batchDetails.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Feature #", None))
        item = self.batchDetails.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Consensus Group", None))
        item = self.batchDetails.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Assignment", None))
        item = self.batchDetails.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Assignment ppm", None))
        item = self.batchDetails.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Avg m/z", None))
        item = self.batchDetails.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Avg RT (s)", None))
        item = self.batchDetails.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Avg IntO", None))
        item = self.batchDetails.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Filled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Batch Tables", None))
        self.label_3.setText(_translate("Dialog", "Feature Alignment", None))
        self.label_4.setText(_translate("Dialog", "Intensity Map", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidget_2Page2), _translate("Dialog", "Group", None))
        self.label_7.setText(_translate("Dialog", "Samples", None))
        self.filledOnly.setText(_translate("Dialog", "Filled Only", None))
        item = self.sampleDetails.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Batch", None))
        item = self.sampleDetails.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Sample", None))
        item = self.sampleDetails.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "m/z", None))
        item = self.sampleDetails.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "RT (s)", None))
        item = self.sampleDetails.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Filled", None))
        item = self.sampleDetails.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "IntO", None))
        item = self.sampleDetails.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "MaxO", None))
        self.activeBatchesGroupBox.setTitle(_translate("Dialog", "Active Batches", None))
        self.groupBox.setTitle(_translate("Dialog", "Integrations", None))
        self.reIntegrateRegion.setText(_translate("Dialog", "Reintegrate Selected Region", None))
        self.restoreDefaultIntegrationButton.setText(_translate("Dialog", "Restore Default Integration", None))
        item = self.assignmentTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Assignment", None))
        item = self.assignmentTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ppm Error", None))
        item = self.assignmentTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "RT Error (s)", None))
        self.pushButton_4.setText(_translate("Dialog", "Add New Assignment", None))
        self.updateAssignment.setText(_translate("Dialog", "Update Assignment", None))
        self.label_11.setText(_translate("Dialog", "Annotations", None))
        self.label_8.setText(_translate("Dialog", "EIC", None))
        self.selectedSamplesOnly.setText(_translate("Dialog", "Show Selected Samples Only", None))
        self.label_9.setText(_translate("Dialog", "MS", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Sample), _translate("Dialog", "Sample", None))
        self.label.setText(_translate("Dialog", "Consensus Group", None))
        self.recoverALLMissingConsensusCandidatesButton.setText(_translate("Dialog", "Recover ALL Missing Candidates", None))
        self.recoverMissingConsensusCandidatesButton.setText(_translate("Dialog", "Recover Missing Consensus Candidates", None))
        self.deleteConsensusGroupButton.setText(_translate("Dialog", "Delete Consensus Group", None))
        self.undoDeleteConsensusGroupButton.setText(_translate("Dialog", "Undo Consensus deletion", None))
        item = self.consensusFeatures.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Group", None))
        item = self.consensusFeatures.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Avg m/z", None))
        item = self.consensusFeatures.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Avg RT (s)", None))
        item = self.consensusFeatures.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Avg IntO", None))
        item = self.consensusFeatures.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "IntO STDEV", None))
        item = self.consensusFeatures.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Num. FIlled", None))
        item = self.consensusFeatures.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Assignment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Feature Review", None))
        self.label_10.setText(_translate("Dialog", "Output File Name", None))
        self.browseResults.setText(_translate("Dialog", "Browse", None))
        self.label_16.setText(_translate("Dialog", "Output File Type(s)", None))
        self.csvOutputCB.setText(_translate("Dialog", "csv", None))
        self.xlsxOutputCB.setText(_translate("Dialog", "xlsx", None))
        self.saveResults.setText(_translate("Dialog", "Save Resutls", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Output", None))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

