# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesAndFeaturesWidget2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(676, 774)
        DockWidget.setWindowTitle(_fromUtf8(""))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 658, 669))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.page)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.loadResults = QtGui.QPushButton(self.groupBox_2)
        self.loadResults.setObjectName(_fromUtf8("loadResults"))
        self.horizontalLayout_6.addWidget(self.loadResults)
        self.closeResults = QtGui.QPushButton(self.groupBox_2)
        self.closeResults.setObjectName(_fromUtf8("closeResults"))
        self.horizontalLayout_6.addWidget(self.closeResults)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.openDataFilesTable = QtGui.QTableWidget(self.groupBox_2)
        self.openDataFilesTable.setObjectName(_fromUtf8("openDataFilesTable"))
        self.openDataFilesTable.setColumnCount(2)
        self.openDataFilesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.openDataFilesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.openDataFilesTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.openDataFilesTable)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.libMatchRTError = QtGui.QLineEdit(self.groupBox)
        self.libMatchRTError.setObjectName(_fromUtf8("libMatchRTError"))
        self.gridLayout_3.addWidget(self.libMatchRTError, 2, 2, 1, 1)
        self.libMatchPPMError = QtGui.QLineEdit(self.groupBox)
        self.libMatchPPMError.setObjectName(_fromUtf8("libMatchPPMError"))
        self.gridLayout_3.addWidget(self.libMatchPPMError, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.posIonCB = QtGui.QCheckBox(self.groupBox)
        self.posIonCB.setObjectName(_fromUtf8("posIonCB"))
        self.horizontalLayout_4.addWidget(self.posIonCB)
        self.negIonCB = QtGui.QCheckBox(self.groupBox)
        self.negIonCB.setChecked(True)
        self.negIonCB.setObjectName(_fromUtf8("negIonCB"))
        self.horizontalLayout_4.addWidget(self.negIonCB)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 2, 1, 1)
        self.selectLibFile = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectLibFile.sizePolicy().hasHeightForWidth())
        self.selectLibFile.setSizePolicy(sizePolicy)
        self.selectLibFile.setObjectName(_fromUtf8("selectLibFile"))
        self.gridLayout_3.addWidget(self.selectLibFile, 0, 0, 1, 1)
        self.libFileText = QtGui.QLabel(self.groupBox)
        self.libFileText.setMaximumSize(QtCore.QSize(600, 16777215))
        self.libFileText.setObjectName(_fromUtf8("libFileText"))
        self.gridLayout_3.addWidget(self.libFileText, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.annotateFromLib = QtGui.QPushButton(self.groupBox)
        self.annotateFromLib.setObjectName(_fromUtf8("annotateFromLib"))
        self.verticalLayout_2.addWidget(self.annotateFromLib)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.page)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.writeAnnotedOnlyCB = QtGui.QCheckBox(self.groupBox_3)
        self.writeAnnotedOnlyCB.setObjectName(_fromUtf8("writeAnnotedOnlyCB"))
        self.gridLayout_4.addWidget(self.writeAnnotedOnlyCB, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.outputFileBrowseButton = QtGui.QPushButton(self.groupBox_3)
        self.outputFileBrowseButton.setObjectName(_fromUtf8("outputFileBrowseButton"))
        self.gridLayout_4.addWidget(self.outputFileBrowseButton, 0, 1, 1, 1)
        self.writePickleFileCB = QtGui.QCheckBox(self.groupBox_3)
        self.writePickleFileCB.setObjectName(_fromUtf8("writePickleFileCB"))
        self.gridLayout_4.addWidget(self.writePickleFileCB, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.saveResults = QtGui.QPushButton(self.groupBox_3)
        self.saveResults.setObjectName(_fromUtf8("saveResults"))
        self.gridLayout_5.addWidget(self.saveResults, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 658, 669))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout = QtGui.QGridLayout(self.page_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_13 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.limitToAnnotatedCB = QtGui.QCheckBox(self.page_3)
        self.limitToAnnotatedCB.setChecked(False)
        self.limitToAnnotatedCB.setObjectName(_fromUtf8("limitToAnnotatedCB"))
        self.horizontalLayout.addWidget(self.limitToAnnotatedCB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.allFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.allFeaturesRB.setObjectName(_fromUtf8("allFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.allFeaturesRB)
        self.unassignedFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.unassignedFeaturesRB.setChecked(True)
        self.unassignedFeaturesRB.setObjectName(_fromUtf8("unassignedFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.unassignedFeaturesRB)
        self.acceptedFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.acceptedFeaturesRB.setObjectName(_fromUtf8("acceptedFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.acceptedFeaturesRB)
        self.rejectedFeaturesRB = QtGui.QRadioButton(self.page_3)
        self.rejectedFeaturesRB.setObjectName(_fromUtf8("rejectedFeaturesRB"))
        self.horizontalLayout_5.addWidget(self.rejectedFeaturesRB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.xcmsFeatures = QtGui.QTableWidget(self.page_3)
        self.xcmsFeatures.setObjectName(_fromUtf8("xcmsFeatures"))
        self.xcmsFeatures.setColumnCount(5)
        self.xcmsFeatures.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.xcmsFeatures.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.xcmsFeatures)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.toolBox, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        self.groupBox_2.setTitle(_translate("DockWidget", "Select XCMS Files", None))
        self.loadResults.setText(_translate("DockWidget", "Load File", None))
        self.closeResults.setText(_translate("DockWidget", "Close File", None))
        item = self.openDataFilesTable.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "#", None))
        item = self.openDataFilesTable.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "File", None))
        self.groupBox.setTitle(_translate("DockWidget", "Annotate Features From Library File", None))
        self.label_2.setText(_translate("DockWidget", "Allowed ppm error", None))
        self.label_3.setText(_translate("DockWidget", "Allowed RT error (Sec)", None))
        self.label.setText(_translate("DockWidget", "Ion Polarity", None))
        self.libMatchRTError.setText(_translate("DockWidget", "240", None))
        self.libMatchPPMError.setText(_translate("DockWidget", "20", None))
        self.posIonCB.setText(_translate("DockWidget", "Pos", None))
        self.negIonCB.setText(_translate("DockWidget", "Neg", None))
        self.selectLibFile.setText(_translate("DockWidget", "Select Library File", None))
        self.libFileText.setText(_translate("DockWidget", "None", None))
        self.annotateFromLib.setText(_translate("DockWidget", "Annotate selected Results File", None))
        self.groupBox_3.setTitle(_translate("DockWidget", "Save Results", None))
        self.writeAnnotedOnlyCB.setText(_translate("DockWidget", "Write Annotated Only", None))
        self.label_4.setText(_translate("DockWidget", "Select Output File", None))
        self.outputFileBrowseButton.setText(_translate("DockWidget", "Browse", None))
        self.writePickleFileCB.setText(_translate("DockWidget", "Write Pickle File", None))
        self.saveResults.setText(_translate("DockWidget", "Save Results", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("DockWidget", "XCMS Results Files", None))
        self.label_13.setText(_translate("DockWidget", "Feature Type", None))
        self.limitToAnnotatedCB.setText(_translate("DockWidget", "Limit to Annotated", None))
        self.allFeaturesRB.setText(_translate("DockWidget", "All", None))
        self.unassignedFeaturesRB.setText(_translate("DockWidget", "Unassigned", None))
        self.acceptedFeaturesRB.setText(_translate("DockWidget", "Accepted", None))
        self.rejectedFeaturesRB.setText(_translate("DockWidget", "Rejected", None))
        item = self.xcmsFeatures.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "File", None))
        item = self.xcmsFeatures.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "#", None))
        item = self.xcmsFeatures.horizontalHeaderItem(2)
        item.setText(_translate("DockWidget", "RT", None))
        item = self.xcmsFeatures.horizontalHeaderItem(3)
        item.setText(_translate("DockWidget", "m/z", None))
        item = self.xcmsFeatures.horizontalHeaderItem(4)
        item.setText(_translate("DockWidget", "Filled", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("DockWidget", "Features", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DockWidget = QtGui.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())

