# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'peakRecoveryDock.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(1001, 718)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        DockWidget.setFont(font)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.putativeAnnotationLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.putativeAnnotationLabel.setFont(font)
        self.putativeAnnotationLabel.setText(_fromUtf8(""))
        self.putativeAnnotationLabel.setObjectName(_fromUtf8("putativeAnnotationLabel"))
        self.gridLayout_3.addWidget(self.putativeAnnotationLabel, 1, 2, 1, 1)
        self.annotationCandidates = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.annotationCandidates.setFont(font)
        self.annotationCandidates.setText(_fromUtf8(""))
        self.annotationCandidates.setObjectName(_fromUtf8("annotationCandidates"))
        self.gridLayout_3.addWidget(self.annotationCandidates, 3, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.selectedSampleOnly = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.selectedSampleOnly.setFont(font)
        self.selectedSampleOnly.setObjectName(_fromUtf8("selectedSampleOnly"))
        self.horizontalLayout_2.addWidget(self.selectedSampleOnly)
        self.setIntegrationBoundaries = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.setIntegrationBoundaries.setFont(font)
        self.setIntegrationBoundaries.setObjectName(_fromUtf8("setIntegrationBoundaries"))
        self.horizontalLayout_2.addWidget(self.setIntegrationBoundaries)
        self.restoreDefaultIntegrationButton = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.restoreDefaultIntegrationButton.setFont(font)
        self.restoreDefaultIntegrationButton.setObjectName(_fromUtf8("restoreDefaultIntegrationButton"))
        self.horizontalLayout_2.addWidget(self.restoreDefaultIntegrationButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.eicPlotFI = GraphicsLayoutWidget(self.widget)
        self.eicPlotFI.setObjectName(_fromUtf8("eicPlotFI"))
        self.verticalLayout_3.addWidget(self.eicPlotFI)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_4.addWidget(self.label_13)
        self.spectrumPlotFI = GraphicsLayoutWidget(self.widget)
        self.spectrumPlotFI.setObjectName(_fromUtf8("spectrumPlotFI"))
        self.verticalLayout_4.addWidget(self.spectrumPlotFI)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.filledOnlyCB = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.filledOnlyCB.setFont(font)
        self.filledOnlyCB.setObjectName(_fromUtf8("filledOnlyCB"))
        self.gridLayout.addWidget(self.filledOnlyCB, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.filledPeaksTable = QtGui.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.filledPeaksTable.setFont(font)
        self.filledPeaksTable.setObjectName(_fromUtf8("filledPeaksTable"))
        self.filledPeaksTable.setColumnCount(6)
        self.filledPeaksTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.filledPeaksTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.filledPeaksTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.filledPeaksTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.filledPeaksTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.filledPeaksTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.filledPeaksTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.filledPeaksTable)
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.intensityDistribution = GraphicsLayoutWidget(self.tab_2)
        self.intensityDistribution.setObjectName(_fromUtf8("intensityDistribution"))
        self.gridLayout_8.addWidget(self.intensityDistribution, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.peakDistributionLayout = GraphicsLayoutWidget(self.tab_3)
        self.peakDistributionLayout.setObjectName(_fromUtf8("peakDistributionLayout"))
        self.verticalLayout_6.addWidget(self.peakDistributionLayout)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.assignmentCandidateTable = QtGui.QTableWidget(self.tab_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.assignmentCandidateTable.setFont(font)
        self.assignmentCandidateTable.setObjectName(_fromUtf8("assignmentCandidateTable"))
        self.assignmentCandidateTable.setColumnCount(3)
        self.assignmentCandidateTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.assignmentCandidateTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.assignmentCandidateTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.assignmentCandidateTable.setHorizontalHeaderItem(2, item)
        self.gridLayout_5.addWidget(self.assignmentCandidateTable, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.acceptAssignment = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.acceptAssignment.setFont(font)
        self.acceptAssignment.setObjectName(_fromUtf8("acceptAssignment"))
        self.horizontalLayout.addWidget(self.acceptAssignment)
        self.clearAssignment = QtGui.QPushButton(self.tab_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.clearAssignment.setFont(font)
        self.clearAssignment.setObjectName(_fromUtf8("clearAssignment"))
        self.horizontalLayout.addWidget(self.clearAssignment)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "Feature Inspector", None))
        self.label_7.setText(_translate("DockWidget", "Annotation", None))
        self.label_12.setText(_translate("DockWidget", "Annotation Candidates", None))
        self.label_11.setText(_translate("DockWidget", "EIC", None))
        self.selectedSampleOnly.setText(_translate("DockWidget", "Selected Only", None))
        self.setIntegrationBoundaries.setText(_translate("DockWidget", "Reintegrate", None))
        self.restoreDefaultIntegrationButton.setText(_translate("DockWidget", "Restore Default", None))
        self.label_13.setText(_translate("DockWidget", "MS", None))
        self.label_9.setText(_translate("DockWidget", "Filters:", None))
        self.filledOnlyCB.setText(_translate("DockWidget", "Filled only", None))
        self.label_6.setText(_translate("DockWidget", "Peaks", None))
        item = self.filledPeaksTable.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "#", None))
        item = self.filledPeaksTable.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "RT", None))
        item = self.filledPeaksTable.horizontalHeaderItem(2)
        item.setText(_translate("DockWidget", "m/z", None))
        item = self.filledPeaksTable.horizontalHeaderItem(3)
        item.setText(_translate("DockWidget", "IntO", None))
        item = self.filledPeaksTable.horizontalHeaderItem(4)
        item.setText(_translate("DockWidget", "MaxO", None))
        item = self.filledPeaksTable.horizontalHeaderItem(5)
        item.setText(_translate("DockWidget", "Filled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DockWidget", "Intensity Distribution", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DockWidget", "Peak Distribution", None))
        item = self.assignmentCandidateTable.horizontalHeaderItem(0)
        item.setText(_translate("DockWidget", "Name", None))
        item = self.assignmentCandidateTable.horizontalHeaderItem(1)
        item.setText(_translate("DockWidget", "ppm Error", None))
        item = self.assignmentCandidateTable.horizontalHeaderItem(2)
        item.setText(_translate("DockWidget", "RT Error", None))
        self.acceptAssignment.setText(_translate("DockWidget", "Accept Selected Assignment", None))
        self.clearAssignment.setText(_translate("DockWidget", "Clear Assignment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("DockWidget", "Assignments", None))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DockWidget = QtGui.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())

