# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'targetedSearch.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1137, 795)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_3 = QtGui.QSplitter(Dialog)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget = QtGui.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mzTolEntry = QtGui.QLineEdit(self.groupBox)
        self.mzTolEntry.setObjectName(_fromUtf8("mzTolEntry"))
        self.gridLayout.addWidget(self.mzTolEntry, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.rtDisplayEntry = QtGui.QLineEdit(self.groupBox)
        self.rtDisplayEntry.setObjectName(_fromUtf8("rtDisplayEntry"))
        self.gridLayout.addWidget(self.rtDisplayEntry, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.browseButton = QtGui.QPushButton(self.groupBox)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.gridLayout_2.addWidget(self.browseButton, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.addDataFilesButton = QtGui.QPushButton(self.groupBox)
        self.addDataFilesButton.setObjectName(_fromUtf8("addDataFilesButton"))
        self.gridLayout_2.addWidget(self.addDataFilesButton, 3, 0, 1, 2)
        self.extractEICsButton = QtGui.QPushButton(self.groupBox)
        self.extractEICsButton.setObjectName(_fromUtf8("extractEICsButton"))
        self.gridLayout_2.addWidget(self.extractEICsButton, 4, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.refStandardsTable = QtGui.QTableWidget(self.layoutWidget)
        self.refStandardsTable.setObjectName(_fromUtf8("refStandardsTable"))
        self.refStandardsTable.setColumnCount(4)
        self.refStandardsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.refStandardsTable, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.eicPlot = GraphicsLayoutWidget(self.splitter_2)
        self.eicPlot.setObjectName(_fromUtf8("eicPlot"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.samplesTable = QtGui.QTableWidget(self.splitter)
        self.samplesTable.setObjectName(_fromUtf8("samplesTable"))
        self.samplesTable.setColumnCount(1)
        self.samplesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.samplesTable.setHorizontalHeaderItem(0, item)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.selectedOnlyCB = QtGui.QCheckBox(self.layoutWidget1)
        self.selectedOnlyCB.setObjectName(_fromUtf8("selectedOnlyCB"))
        self.verticalLayout_2.addWidget(self.selectedOnlyCB)
        self.showIntegrationCB = QtGui.QCheckBox(self.layoutWidget1)
        self.showIntegrationCB.setObjectName(_fromUtf8("showIntegrationCB"))
        self.verticalLayout_2.addWidget(self.showIntegrationCB)
        self.showSpectrumCB = QtGui.QCheckBox(self.layoutWidget1)
        self.showSpectrumCB.setObjectName(_fromUtf8("showSpectrumCB"))
        self.verticalLayout_2.addWidget(self.showSpectrumCB)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addWidget(self.splitter_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Standards Search", None))
        self.label_4.setText(_translate("Dialog", "EIC Parameters", None))
        self.label_2.setText(_translate("Dialog", "m/z width (Th)", None))
        self.label_3.setText(_translate("Dialog", "RT width (s)", None))
        self.browseButton.setText(_translate("Dialog", "Browse", None))
        self.label.setText(_translate("Dialog", "Library File", None))
        self.addDataFilesButton.setText(_translate("Dialog", "Add data files", None))
        self.extractEICsButton.setText(_translate("Dialog", "Extract EICs", None))
        self.label_5.setText(_translate("Dialog", "Reference Standards", None))
        item = self.refStandardsTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "#", None))
        item = self.refStandardsTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name", None))
        item = self.refStandardsTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "RT", None))
        item = self.refStandardsTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "m/z", None))
        item = self.samplesTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "File name", None))
        self.label_6.setText(_translate("Dialog", "View Controls", None))
        self.selectedOnlyCB.setText(_translate("Dialog", "Show Selected", None))
        self.showIntegrationCB.setText(_translate("Dialog", "Show Integration", None))
        self.showSpectrumCB.setText(_translate("Dialog", "Show Spectrum", None))
        self.label_7.setText(_translate("Dialog", "Integration Controls", None))
        self.pushButton_3.setText(_translate("Dialog", "Integrate Region", None))
        self.pushButton_4.setText(_translate("Dialog", "Accept Peak", None))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

