# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'targetedExplorerDock.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TargetExplorer(object):
    def setupUi(self, TargetExplorer):
        TargetExplorer.setObjectName(_fromUtf8("TargetExplorer"))
        TargetExplorer.resize(1292, 809)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        TargetExplorer.setFont(font)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.standardTable = QtGui.QTableWidget(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.standardTable.setFont(font)
        self.standardTable.setObjectName(_fromUtf8("standardTable"))
        self.standardTable.setColumnCount(7)
        self.standardTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.standardTable.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.standardTable, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitter_3 = QtGui.QSplitter(self.tab_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget = QtGui.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.rtDisplayEntry = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rtDisplayEntry.setFont(font)
        self.rtDisplayEntry.setObjectName(_fromUtf8("rtDisplayEntry"))
        self.gridLayout_6.addWidget(self.rtDisplayEntry, 1, 1, 1, 1)
        self.mzTolEntry = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mzTolEntry.setFont(font)
        self.mzTolEntry.setObjectName(_fromUtf8("mzTolEntry"))
        self.gridLayout_6.addWidget(self.mzTolEntry, 0, 1, 1, 1)
        self.extractEICsButton = QtGui.QPushButton(self.groupBox)
        self.extractEICsButton.setObjectName(_fromUtf8("extractEICsButton"))
        self.gridLayout_6.addWidget(self.extractEICsButton, 2, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.refStandardsTable = QtGui.QTableWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.refStandardsTable.setFont(font)
        self.refStandardsTable.setObjectName(_fromUtf8("refStandardsTable"))
        self.refStandardsTable.setColumnCount(4)
        self.refStandardsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.refStandardsTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_7.addWidget(self.refStandardsTable, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.eicPlot = GraphicsLayoutWidget(self.splitter_2)
        self.eicPlot.setObjectName(_fromUtf8("eicPlot"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.samplesTable = QtGui.QTableWidget(self.splitter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.samplesTable.setFont(font)
        self.samplesTable.setObjectName(_fromUtf8("samplesTable"))
        self.samplesTable.setColumnCount(3)
        self.samplesTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.samplesTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.samplesTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.samplesTable.setHorizontalHeaderItem(2, item)
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10)
        self.selectedOnlyCB = QtGui.QCheckBox(self.layoutWidget_2)
        self.selectedOnlyCB.setObjectName(_fromUtf8("selectedOnlyCB"))
        self.verticalLayout_2.addWidget(self.selectedOnlyCB)
        self.showIntegrationCB = QtGui.QCheckBox(self.layoutWidget_2)
        self.showIntegrationCB.setObjectName(_fromUtf8("showIntegrationCB"))
        self.verticalLayout_2.addWidget(self.showIntegrationCB)
        self.showSpectrumCB = QtGui.QCheckBox(self.layoutWidget_2)
        self.showSpectrumCB.setObjectName(_fromUtf8("showSpectrumCB"))
        self.verticalLayout_2.addWidget(self.showSpectrumCB)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_11 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.integrateRegionButton = QtGui.QPushButton(self.layoutWidget_2)
        self.integrateRegionButton.setObjectName(_fromUtf8("integrateRegionButton"))
        self.verticalLayout_3.addWidget(self.integrateRegionButton)
        self.clearIntegrationButton = QtGui.QPushButton(self.layoutWidget_2)
        self.clearIntegrationButton.setObjectName(_fromUtf8("clearIntegrationButton"))
        self.verticalLayout_3.addWidget(self.clearIntegrationButton)
        self.acceptPeakButton = QtGui.QPushButton(self.layoutWidget_2)
        self.acceptPeakButton.setObjectName(_fromUtf8("acceptPeakButton"))
        self.verticalLayout_3.addWidget(self.acceptPeakButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        TargetExplorer.setWidget(self.dockWidgetContents)

        self.retranslateUi(TargetExplorer)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TargetExplorer)

    def retranslateUi(self, TargetExplorer):
        TargetExplorer.setWindowTitle(_translate("TargetExplorer", "Target Explorer", None))
        item = self.standardTable.horizontalHeaderItem(0)
        item.setText(_translate("TargetExplorer", "#", None))
        item = self.standardTable.horizontalHeaderItem(1)
        item.setText(_translate("TargetExplorer", "Compound", None))
        item = self.standardTable.horizontalHeaderItem(2)
        item.setText(_translate("TargetExplorer", "Match", None))
        item = self.standardTable.horizontalHeaderItem(3)
        item.setText(_translate("TargetExplorer", "Ref RT", None))
        item = self.standardTable.horizontalHeaderItem(4)
        item.setText(_translate("TargetExplorer", "RT Error", None))
        item = self.standardTable.horizontalHeaderItem(5)
        item.setText(_translate("TargetExplorer", "Ref m/z", None))
        item = self.standardTable.horizontalHeaderItem(6)
        item.setText(_translate("TargetExplorer", "m/z Error", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TargetExplorer", "Targets", None))
        self.groupBox.setTitle(_translate("TargetExplorer", "EIC Parameters", None))
        self.label_7.setText(_translate("TargetExplorer", "RT width (s)", None))
        self.label_6.setText(_translate("TargetExplorer", "m/z width (Th)", None))
        self.extractEICsButton.setText(_translate("TargetExplorer", "Extract EICs", None))
        self.label_9.setText(_translate("TargetExplorer", "Reference Standards", None))
        item = self.refStandardsTable.horizontalHeaderItem(0)
        item.setText(_translate("TargetExplorer", "#", None))
        item = self.refStandardsTable.horizontalHeaderItem(1)
        item.setText(_translate("TargetExplorer", "Name", None))
        item = self.refStandardsTable.horizontalHeaderItem(2)
        item.setText(_translate("TargetExplorer", "RT", None))
        item = self.refStandardsTable.horizontalHeaderItem(3)
        item.setText(_translate("TargetExplorer", "m/z", None))
        item = self.samplesTable.horizontalHeaderItem(0)
        item.setText(_translate("TargetExplorer", "#", None))
        item = self.samplesTable.horizontalHeaderItem(1)
        item.setText(_translate("TargetExplorer", "File name", None))
        item = self.samplesTable.horizontalHeaderItem(2)
        item.setText(_translate("TargetExplorer", "IntO", None))
        self.label_10.setText(_translate("TargetExplorer", "View Controls", None))
        self.selectedOnlyCB.setText(_translate("TargetExplorer", "Show Selected", None))
        self.showIntegrationCB.setText(_translate("TargetExplorer", "Show Integration", None))
        self.showSpectrumCB.setText(_translate("TargetExplorer", "Show Spectrum", None))
        self.label_11.setText(_translate("TargetExplorer", "Integration Controls", None))
        self.integrateRegionButton.setText(_translate("TargetExplorer", "Integrate Region", None))
        self.clearIntegrationButton.setText(_translate("TargetExplorer", "Clear Integration", None))
        self.acceptPeakButton.setText(_translate("TargetExplorer", "Accept Peak", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TargetExplorer", "Explorer", None))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TargetExplorer = QtGui.QDockWidget()
    ui = Ui_TargetExplorer()
    ui.setupUi(TargetExplorer)
    TargetExplorer.show()
    sys.exit(app.exec_())

